spring.application.name=SpringBoot_24_March_Assignment
spring.datasource.username=root
spring.datasource.password=Abhirat@87654321
spring.datasource.url=jdbc:mysql://localhost:3306/ps23
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

